Repository phovea/phovea_security_store_ldap, pull requests merged in 2020-01, with the labels that each got.

#13 Migrate to Python 3.7
  .circleci/config.yml
  .gitlab-ci.yml
  .travis.yml
  phovea_security_store_ldap/ldap.py
  phovea_security_store_ldap/main.py
  requirements.txt
  requirements_dev.txt
  setup.py
  tox.ini
Labels: release: major, type: refactor

#17 Release 4.0.0
  .circleci/config.yml
  .gitignore
  .gitlab-ci.yml
  .travis.yml
  package-lock.json
  package.json
  phovea_security_store_ldap/ldap.py
  phovea_security_store_ldap/main.py
  requirements.txt
  requirements_dev.txt
  setup.py
  tox.ini
Labels: release: major

#18 Fix LDAP and Python 3.7 issues
  phovea_security_store_ldap/ldap.py
  setup.py
Labels: priority: high, type: bug, type: deployment

#20 Use log.info() instead of log.debug()
  phovea_security_store_ldap/ldap.py
Labels: type: refactor

#24 Revert changes of logging level for testing
  phovea_security_store_ldap/ldap.py
Labels: type: refactor
